[package]
name = "turbo_fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking"] }
tokio = { version = "1.38.0", features = ["full"] }
futures = { version = "0.3" }